# config/constants.py
"""
כאן יש ריכוז של כל המשתנים הקבועים בעבור איטריצה 1

"""
EMPTY_SQUARE = '.'
VALID_COLORS = {'w', 'b'}
VALID_PIECES = {'K', 'Q', 'R', 'B', 'N', 'P'}
MILLISECONDS_PER_CELL = 1000
JUMP_DURATION_MILLISECONDS = 1000
CELL_SIZE = 100

BOARD_SECTION_HEADER = "Board:"
COMMANDS_SECTION_HEADER = "Commands:"

COMMAND_CLICK = "click"
COMMAND_JUMP = "jump"
COMMAND_WAIT = "wait"
COMMAND_PRINT_BOARD = "print board"

ERR_UNKNOWN_TOKEN = "ERROR UNKNOWN_TOKEN"
ERR_ROW_WIDTH_MISMATCH = "ERROR ROW_WIDTH_MISMATCH"
ERR_EMPTY_COMMAND = "ERROR EMPTY_COMMAND"
ERR_UNKNOWN_COMMAND = "ERROR UNKNOWN_COMMAND"
ERR_CLICK_OUTSIDE_BOARD = "ERROR CLICK_OUTSIDE_BOARD"
ERR_CLICK_EMPTY_SOURCE = "ERROR CLICK_EMPTY_SOURCE"
ERR_JUMP_OUTSIDE_BOARD = "ERROR JUMP_OUTSIDE_BOARD"
ERR_JUMP_EMPTY_SOURCE = "ERROR JUMP_EMPTY_SOURCE"
ERR_GAME_OVER = "ERROR GAME_OVER"
ERR_MOTION_IN_PROGRESS = "ERROR MOTION_IN_PROGRESS"
ERR_EMPTY_SOURCE = "ERROR EMPTY_SOURCE"
ERR_FRIENDLY_DESTINATION = "ERROR FRIENDLY_DESTINATION"
ERR_ILLEGAL_PIECE_MOVE = "ERROR ILLEGAL_PIECE_MOVE"


